# Generated by Django 5.1.1 on 2024-10-08 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MjbilAlRai_App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='completion_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ اكتمال الحجز'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='is_completed',
            field=models.BooleanField(default=False, verbose_name='الحجز مكتمل'),
        ),
    ]
