# Generated by Django 5.1.1 on 2024-10-08 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MjbilAlRai_App', '0002_reservation_completion_date_reservation_is_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='total_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='إجمالي التكلفة قبل الخصم (دولار أمريكي)'),
        ),
    ]
