# Generated by Django 5.1.1 on 2024-10-09 08:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MjbilAlRai_App', '0003_alter_reservation_total_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='concrete_type',
            field=models.CharField(choices=[('150', 'عيار 150 كغ'), ('200', 'عيار 200 كغ'), ('250', 'عيار 250 كغ'), ('300', 'عيار 300 كغ'), ('350', 'عيار 350 كغ'), ('400', 'عيار 400 كغ'), ('450', 'عيار 450 كغ'), ('500', 'عيار 500 كغ')], max_length=100, verbose_name='نوع الخرسانة'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='phone_number',
            field=models.CharField(help_text="يجب إدخال رقم الهاتف بصيغة: '+999999999'. يمكن إدخال ما يصل إلى 15 رقماً.", max_length=15, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{9,15}$')], verbose_name='رقم الهاتف'),
        ),
    ]
