# Generated by Django 5.1.1 on 2024-10-09 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MjbilAlRai_App', '0004_alter_reservation_concrete_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'permissions': [('can_manage_reservations', 'يمكنه إدارة الحجوزات'), ('can_confirm_reservations', 'يمكنه تأكيد الحجوزات'), ('can_manage_accountant', 'يمكنه إدارة صفحات المحاسب')]},
        ),
        migrations.AddField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('معلق', 'معلق'), ('مقبول', 'مقبول'), ('مكتمل', 'مكتمل'), ('مرفوض', 'مرفوض')], default='معلق', max_length=20, verbose_name='حالة الحجز'),
        ),
    ]
